server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_manage?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cache:
    redis:
      time-to-live: 10s
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  global-config:
    db-config:
      table-prefix: job_
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    root: error
