server:
  port: 20233
spring:
  sql:
    init:
      continue-on-error: true
      schema-locations:
        - classpath:/sql/job_manage-schema.sql
      mode: always
      data-locations:
        - classpath:/sql/job_manage-data.sql
  datasource:
    url: jdbc:mysql://localhost:3306/job_manage?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cache:
    redis:
      time-to-live: 10s
  redis:
    host: localhost
    port: 6379
  main:
    banner-mode: off
  jackson:
    # 设置时区为东八区，否则获取到前端传入的时间会出现时区差8小时的问题
    time-zone: GMT+8
    date-format: "yyyy-MM-dd HH:mm:ss"
  mail:
    host: smtp.qq.com
    username: csgzs@foxmail.com
    password: dlqalcdzhwdfdgfg
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  mvc:
    servlet:
      load-on-startup: 1
mybatis-plus:
  global-config:
    db-config:
      table-prefix: job_
    banner: false
  mapper-locations: classpath*:/mapper/**/*.xml
job-manage-settings:
  work-folder-name: "JobManage"
